version: '3'
services:
  backend:
    container_name: app-backend
    build: ./backend
    ports:
      - '3001:3001'
    working_dir: /app-backend
    depends_on:
      - db
    environment:
      - PORT=3001
      - SECRET=jwt_secret
      - SALT=12
      - MONGO_URL=mongodb://root:12345678@db:27017/allugator?authSource=admin

  db:
    image: mongo:6.0.2
    container_name: db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    restart: 'always'

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345678
      ME_CONFIG_MONGODB_URL: mongodb://root:12345678@db:27017/
